In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 52.8 MB/s  0:00:006m0:00:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 60.6 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['홍길동', '김철수', '이영희'],
    '학년': ['1', '2', '3'],
    '학과': ['컴퓨터공학', '전자공학', '기계공학'],
    '국어': [85, 90, 78],
    '수학': [92, 88, 95],
    '영어': [80, 85, 82]
})

print(df)

    이름 학년     학과  국어  수학  영어
0  홍길동  1  컴퓨터공학  85  92  80
1  김철수  2   전자공학  90  88  85
2  이영희  3   기계공학  78  95  82

In [7]:
print(df.dtypes)

이름      str
학년      str
학과      str
국어    int64
수학    int64
영어    int64
dtype: object

In [12]:
df.describe()

              국어         수학         영어
count   3.000000   3.000000   3.000000
mean   84.333333  91.666667  82.333333
std     6.027714   3.511885   2.516611
min    78.000000  88.000000  80.000000
25%    81.500000  90.000000  81.000000
50%    85.000000  92.000000  82.000000
75%    87.500000  93.500000  83.500000
max    90.000000  95.000000  85.000000

In [14]:
df2=df.set_index('이름')
df2

    학년     학과  국어  수학  영어
이름
홍길동  1  컴퓨터공학  85  92  80
김철수  2   전자공학  90  88  85
이영희  3   기계공학  78  95  82

In [16]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 홍길동 to 이영희
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학년      3 non-null      str
 1   학과      3 non-null      str
 2   국어      3 non-null      int64
 3   수학      3 non-null      int64
 4   영어      3 non-null      int64
dtypes: int64(3), str(2)
memory usage: 144.0+ bytes

In [21]:
df2.loc['홍길동','국어']
df2.loc[:,'국어']
df2.loc['홍길동':'김철수','국어':'영어']
df2.iloc[2,2]
df2.iloc[0:2,0:3]

    학년     학과  국어
이름
홍길동  1  컴퓨터공학  85
김철수  2   전자공학  90

In [22]:
df[df['국어']>=80]

    이름 학년     학과  국어  수학  영어
0  홍길동  1  컴퓨터공학  85  92  80
1  김철수  2   전자공학  90  88  85

In [23]:
import pandas as pd
import numpy as np

df = pd.DataFrame({

    '이름': ['홍길동', '김철수', '이영희'],
    '학년': ['1', '2', '3'],
    '학과': ['컴퓨터공학', '전자공학', '기계공학'],
    '국어': [np.nan, 90, 78],
    '수학': [92, np.nan, 95],
    '영어': [80, 85, np.nan]
})

df

    이름 학년     학과    국어    수학    영어
0  홍길동  1  컴퓨터공학   NaN  92.0  80.0
1  김철수  2   전자공학  90.0   NaN  85.0
2  이영희  3   기계공학  78.0  95.0   NaN